# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 05:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.CharField(default='System', editable=False, max_length=100)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_by', models.CharField(default='System', editable=False, max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('section', models.BooleanField(default=False, verbose_name='staff status')),
                ('short_section', models.CharField(default=None, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
