# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionhead',
            name='user',
        ),
        migrations.AddField(
            model_name='employee',
            name='section',
            field=models.BooleanField(default=False, verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='employee',
            name='short_section',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.DeleteModel(
            name='SectionHead',
        ),
    ]
