# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 11:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract_mgt', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.CharField(default='System', editable=False, max_length=100)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_by', models.CharField(default='System', editable=False, max_length=100)),
                ('team_task_no', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('contract_no', models.CharField(max_length=100)),
                ('category', models.PositiveIntegerField(default=0)),
                ('status', models.PositiveIntegerField(default=0)),
                ('severity', models.PositiveIntegerField(default=0)),
                ('end_user', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('date_expected', models.DateTimeField(blank=True, null=True)),
                ('date_team_task', models.DateTimeField(blank=True, null=True)),
                ('date_close', models.DateTimeField(blank=True, null=True)),
                ('classification', models.PositiveIntegerField(default=0)),
                ('notify', models.PositiveIntegerField(default=0)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_mgt.Contractor')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamTaskHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.CharField(default='System', editable=False, max_length=100)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_by', models.CharField(default='System', editable=False, max_length=100)),
                ('action_taken', models.TextField(blank=True)),
                ('next_action', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('action_taken_by', models.PositiveIntegerField(default=0)),
                ('status', models.PositiveIntegerField(default=0)),
                ('date_expected', models.DateTimeField(blank=True, null=True)),
                ('date_action', models.DateTimeField(blank=True, null=True)),
                ('team_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_mgt.TeamTask')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
