# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 11:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_mgt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamtaskhistory',
            name='action_taken_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
